# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88ca2670d4c9275b7935ba544e6c45193c0c99516fd2c2bc17f6bef8bcde92a4bebd70cbb7f658e2e82645ae36230dd7415fcedc6a388be385eaa611be51363a

test:
  secret_key_base: b1ffd04461fc62c51337fb72285bcaf2c8276994566a97b12b1cbd4ed3d0504556509386c8bc977fc130f29bbacb58fbb97b06f31a23b0d00f987d44e585acae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
